# Generated by Django 6.0.1 on 2026-01-30 19:01

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_repo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=api.models.diagram_image_path)),
                ('diagram_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.diagramversion')),
            ],
        ),
    ]
