# Generated by Django 5.2.4 on 2026-02-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_last_commit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramversion',
            name='readme_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagramimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='diagramversion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
