# Generated by Django 6.0.1 on 2026-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diagramimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_commit_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
