# Generated by Django 5.0.2 on 2026-02-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diagramversion_readme_content_alter_diagramimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramversion',
            name='summary_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
